{
  "Navigation": {
    "products": "Products",
    "categories": "Categories",
    "campaigns": "Campaigns",
    "stores": "Stores",
    "blog": "Blog",
    "agronom": "Agronomist",
    "search_placeholder": "Search products, companies, fertilizers...",
    "dashboard": "Dashboard",
    "logout": "Logout",
    "login": "Login",
    "home": "Home",
    "favorites": "Favorites",
    "messages": "Messages",
    "profile": "Profile",
    "sell": "Sell",
    "brands": "Brands",
    "agroServices": "Agro Services",
    "newListing": "New Listing",
    "register": "Register",
    "compare": "Compare",
    "calculator": "Calculator",
    "diseases": "Diseases",
    "pests": "Pests",
    "crops": "Crops",
    "active_ingredients": "Active Ingredients",
    "sales_points": "Sales Points",
    "cart": "Cart",
    "farmer_club": "Farmer Club",
    "leaderboard": "Leaderboard",
    "about": "About Us",
    "contact": "Contact",
    "terms": "Terms",
    "privacy": "Privacy"
  },
  "Home": {
    "popularBrands": "Popular Brands",
    "popularStores": "Popular Sellers",
    "allCategories": "All Categories",
    "viewAll": "View All",
    "opportunity": "Opportunity!",
    "discountText": "20% discount on all fertilizers",
    "details": "Details",
    "products": "products",
    "newListing": "New Listing",
    "heroTitle": "Agricultural Market Platform",
    "heroSubtitle": "Unified AI-powered marketplace for farmers, stores, agronomists and buyers",
    "searchPlaceholder": "Search products, fertilizers, machinery...",
    "featuredProducts": "Featured Products",
    "latestNews": "Latest News",
    "specialOffers": "Special Offers"
  },
  "common": {
    "loading": "Loading...",
    "error": "An error occurred",
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "edit": "Edit",
    "view_all": "View All",
    "back": "Back",
    "send": "Send",
    "close": "Close",
    "yes": "Yes",
    "no": "No",
    "more": "More",
    "share": "Share",
    "contact": "Contact",
    "address": "Address",
    "region": "Region",
    "city": "City",
    "search": "Search",
    "filter": "Filter",
    "clear": "Clear",
    "submit": "Submit",
    "success": "Completed successfully",
    "actions": "Actions",
    "status": "Status",
    "total": "Total",
    "all": "All",
    "apply": "Apply",
    "reset": "Reset",
    "none": "None",
    "notFound": "Page not found"
  },
  "products": "Products",
  "dashboard": "Dashboard",
  "auth": {
    "email": "Email",
    "password": "Password",
    "full_name": "Full Name",
    "phone": "Phone",
    "sign_in": "Sign In",
    "sign_up": "Sign Up",
    "forgot_password": "Forgot Password?",
    "reset_password": "Reset Password",
    "remember_me": "Remember Me",
    "login_title": "Log in to Account",
    "register_title": "Register",
    "or_continue_with": "or continue with",
    "dont_have_account": "Don't have an account?",
    "already_have_account": "Already have an account?"
  },
  "admin": {
    "users": "Users",
    "products": "Products",
    "categories": "Categories",
    "orders": "Orders",
    "campaigns": "Campaigns",
    "diseases": "Diseases",
    "pests": "Pests",
    "crops": "Crops",
    "active_ingredients": "Active Ingredients",
    "translations": "Translations",
    "settings": "Settings",
    "analytics": "Analytics",
    "delivery": "Delivery",
    "studio": "Studio",
    "actions": "Actions",
    "approve": "Approve",
    "reject": "Reject"
  },
  "footer": {
    "about_us": "About Us",
    "contact_us": "Contact Us",
    "terms_conditions": "Terms & Conditions",
    "privacy_policy": "Privacy Policy",
    "all_rights_reserved": "All rights reserved.",
    "quick_links": "Quick Links",
    "categories": "Categories",
    "connect_with_us": "Social Media"
  },
  "cart": "Cart",
  "checkout": "Checkout",
  "agronom": "AI Agronomist",
  "status": {
    "pending": "Pending",
    "active": "Active",
    "sold": "Sold",
    "rejected": "Rejected",
    "processing": "Processing",
    "shipped": "Shipped",
    "delivered": "Delivered",
    "cancelled": "Cancelled"
  },
  "nav": {
    "products": "Products",
    "categories": "Categories",
    "campaigns": "Campaigns",
    "stores": "Stores",
    "blog": "Blog",
    "agronom": "Agronomist",
    "search_placeholder": "Search products, companies, fertilizers...",
    "dashboard": "Dashboard",
    "logout": "Logout",
    "login": "Login",
    "home": "Home",
    "favorites": "Favorites",
    "messages": "Messages",
    "profile": "Profile",
    "sell": "Sell",
    "brands": "Brands",
    "agroServices": "Agro Services",
    "newListing": "New Listing",
    "register": "Register",
    "compare": "Compare",
    "calculator": "Calculator",
    "diseases": "Diseases",
    "pests": "Pests",
    "crops": "Crops",
    "active_ingredients": "Active Ingredients",
    "sales_points": "Sales Points",
    "cart": "Cart",
    "farmer_club": "Farmer Club",
    "leaderboard": "Leaderboard",
    "about": "About Us",
    "contact": "Contact",
    "terms": "Terms",
    "privacy": "Privacy"
  },
  "home": "Home",
  "Product": {
    "add_to_cart": "Add to Cart",
    "buy_now": "Buy Now",
    "whatsapp_order": "Order via WhatsApp",
    "add_to_compare": "Add to Compare",
    "add_to_favorites": "Add to Favorites",
    "price": "Price",
    "stock": "Stock",
    "category": "Category",
    "seller": "Seller",
    "in_stock": "In Stock",
    "out_of_stock": "Out of Stock",
    "description": "Description",
    "specifications": "Specifications",
    "similar_products": "Similar Products",
    "reviews": "Reviews",
    "rating": "Rating",
    "brand": "Brand",
    "unit": "Unit",
    "report": "Report",
    "quote_request": "Request Quote",
    "credit_request": "Credit Application"
  },
  "Dashboard": {
    "welcome": "Welcome",
    "my_orders": "My Orders",
    "my_products": "My Products",
    "add_product": "Add Product",
    "profile_settings": "Profile Settings",
    "wallet": "Balance",
    "earnings": "Earnings",
    "analytics": "Analytics",
    "delivery_orders": "Delivery Orders",
    "admin_panel": "Admin Panel",
    "catalog": "Catalog",
    "notifications": "Notifications",
    "settings": "Settings",
    "messages": "Messages"
  },
  "Auth": {
    "email": "Email",
    "password": "Password",
    "full_name": "Full Name",
    "phone": "Phone",
    "sign_in": "Sign In",
    "sign_up": "Sign Up",
    "forgot_password": "Forgot Password?",
    "reset_password": "Reset Password",
    "remember_me": "Remember Me",
    "login_title": "Log in to Account",
    "register_title": "Register",
    "or_continue_with": "or continue with",
    "dont_have_account": "Don't have an account?",
    "already_have_account": "Already have an account?"
  },
  "Admin": {
    "users": "Users",
    "products": "Products",
    "categories": "Categories",
    "orders": "Orders",
    "campaigns": "Campaigns",
    "diseases": "Diseases",
    "pests": "Pests",
    "crops": "Crops",
    "active_ingredients": "Active Ingredients",
    "translations": "Translations",
    "settings": "Settings",
    "analytics": "Analytics",
    "delivery": "Delivery",
    "studio": "Studio",
    "actions": "Actions",
    "approve": "Approve",
    "reject": "Reject"
  },
  "Footer": {
    "about_us": "About Us",
    "contact_us": "Contact Us",
    "terms_conditions": "Terms & Conditions",
    "privacy_policy": "Privacy Policy",
    "all_rights_reserved": "All rights reserved.",
    "quick_links": "Quick Links",
    "categories": "Categories",
    "connect_with_us": "Social Media"
  },
  "Cart": {
    "cart": "Cart",
    "cart_empty": "Your cart is empty",
    "checkout": "Proceed to Checkout",
    "total": "Total",
    "quantity": "Quantity",
    "remove": "Remove",
    "subtotal": "Subtotal",
    "delivery_fee": "Delivery Fee",
    "promo_code": "Promo Code",
    "apply_coupon": "Apply"
  },
  "Status": {
    "pending": "Pending",
    "active": "Active",
    "sold": "Sold",
    "rejected": "Rejected",
    "processing": "Processing",
    "shipped": "Shipped",
    "delivered": "Delivered",
    "cancelled": "Cancelled"
  },
  "categories": "Categories",
  "blog": "Blog",
  "stores": "Stores",
  "login": "Login",
  "register": "Register",
  "logout": "Logout",
  "compare": "Compare",
  "calculator": "Calculator",
  "diseases": "Diseases",
  "pests": "Pests",
  "crops": "Crops",
  "active_ingredients": "Active Ingredients",
  "sales_points": "Sales Points",
  "add_to_cart": "Add to Cart",
  "buy_now": "Buy Now",
  "whatsapp_order": "Order via WhatsApp",
  "add_to_compare": "Add to Compare",
  "add_to_favorites": "Add to Favorites",
  "price": "Price",
  "stock": "Stock",
  "category": "Category",
  "seller": "Seller",
  "in_stock": "In Stock",
  "out_of_stock": "Out of Stock",
  "search_placeholder": "Search products, companies, active ingredients...",
  "search_results": "Search Results",
  "no_results": "No results found",
  "trending": "Trending Searches",
  "cart_empty": "Cart is empty",
  "total": "Total",
  "quantity": "Quantity",
  "remove": "Remove",
  "email": "Email",
  "password": "Password",
  "full_name": "Full Name",
  "phone": "Phone",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "forgot_password": "Forgot Password?",
  "pending": "Pending",
  "active": "Active",
  "sold": "Sold",
  "rejected": "Rejected",
  "loading": "Loading...",
  "error": "An error occurred",
  "save": "Save",
  "cancel": "Cancel",
  "delete": "Delete",
  "edit": "Edit",
  "view_all": "View All",
  "back": "Back",
  "send": "Send",
  "close": "Close",
  "yes": "Yes",
  "no": "No",
  "more": "More",
  "share": "Share",
  "contact": "Contact",
  "address": "Address",
  "region": "Region",
  "city": "City"
}