-- AlterTable
ALTER TABLE "Store" ADD COLUMN "email" TEXT,
ADD COLUMN "facebook" TEXT,
ADD COLUMN "instagram" TEXT,
ADD COLUMN "tiktok" TEXT,
ADD COLUMN "linkedin" TEXT,
ADD COLUMN "youtube" TEXT,
ADD COLUMN "telegram" TEXT,
ADD COLUMN "workingHours" JSONB,
ADD COLUMN "deliveryRegions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "taxInfo" TEXT,
ADD COLUMN "bankName" TEXT,
ADD COLUMN "bankAccount" TEXT,
ADD COLUMN "iban" TEXT,
ADD COLUMN "supportEmail" TEXT,
ADD COLUMN "supportPhone" TEXT,
ADD COLUMN "primaryColor" TEXT DEFAULT '#16a34a',
ADD COLUMN "secondaryColor" TEXT,
ADD COLUMN "themeMode" TEXT DEFAULT 'light',
ADD COLUMN "followerCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "storeViewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "totalSales" INTEGER NOT NULL DEFAULT 0;
