-- AlterEnum: Add new values to ModuleKey enum
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'CATEGORIES_SLIDER';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'HERO_SECTION';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'PROMO_BANNER';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'PRODUCTS_GRID';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'BLOG_SECTION';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'TESTIMONIALS';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'NEWSLETTER_SIGNUP';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'WEATHER_WIDGET';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'AGRONOMIST_AI';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'COMPARISON_TOOL';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'FAVORITES';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'DIRECT_MESSAGING';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'WALLET_SYSTEM';
ALTER TYPE "ModuleKey" ADD VALUE IF NOT EXISTS 'STORE_RATINGS';
