import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Bell,
  BellOff,
  Building2,
  Check,
  CheckCheck,
  ChevronDown,
  CircleCheck,
  Cpu,
  Clock,
  CreditCard,
  CircleX,
  ClipboardCheck,
  Heart,
  Home,
  Info,
  LayoutDashboard,
  Lightbulb,
  Link2,
  LogOut,
  MapPin,
  MessageCircle,
  Newspaper,
  Package,
  Plus,
  Search,
  ShoppingCart,
  Sprout,
  Star,
  Trash2,
  Truck,
  UserCircle,
  UserRound,
  WalletCards,
  Send,
  ZoomIn,
  X,
  Apple, Bird, Bug, Carrot, Dog, Droplet, Fish, Leaf, Rabbit, Tractor, Wheat,
  Trees, Milk, Sun, CloudRain, Snowflake, Flame, FileText, FlaskConical, Hexagon, Component, Grid, Tag, Box, Store, ShoppingBasket, CircleDollarSign, FlameKindling, Palmtree,
  TrendingUp,
  Phone,
  Smartphone,
  Trophy,
  Medal,
  Award,
  Gift,
  Key,
  Lock,
  Upload,
  Download,
  Pencil,
  Save,
  Megaphone,
  Target,
  Briefcase,
  BarChart3,
  PieChart,
  Folder,
  Users,
  Mail,
  Inbox,
  Camera,
  Sparkles,
  ShieldCheck,
  Crown,
  Rocket,
  Coins,
  Settings,
  Ban,
  Pause,
  Zap,
  Activity,
  Eye,
  Image,
  Calendar,
  Thermometer,
  Microscope,
  Map,
  Filter,
  Percent,
  Hand,
  Globe,
  RefreshCw,
  Share2,
  Copy,
  File,
  Layers,
  Sliders,
  ThumbsUp,
  UserCheck,
  Shield,
  BadgeCheck,
  GitMerge,
  Loader2,
  Paperclip,
  ShoppingBag,
  Smile
} from "lucide-react";

export const ICONS = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  bell: Bell,
  bellOff: BellOff,
  building: Building2,
  creditCard: CreditCard,
  check: Check,
  checkCheck: CheckCheck,
  checkDouble: CheckCheck,
  chevronDown: ChevronDown,
  checkCircle: CircleCheck,
  bot: Cpu,
  clock: Clock,
  closeCircle: CircleX,
  clipboard: ClipboardCheck,
  heart: Heart,
  home: Home,
  info: Info,
  dashboard: LayoutDashboard,
  lightbulb: Lightbulb,
  link: Link2,
  logout: LogOut,
  mapPin: MapPin,
  message: MessageCircle,
  newspaper: Newspaper,
  package: Package,
  plus: Plus,
  search: Search,
  cart: ShoppingCart,
  sprout: Sprout,
  star: Star,
  trash: Trash2,
  truck: Truck,
  user: UserRound,
  userCircle: UserCircle,
  wallet: WalletCards,
  send: Send,
  zoomIn: ZoomIn,
  close: X,
  apple: Apple,
  bird: Bird,
  bug: Bug,
  carrot: Carrot,
  dog: Dog,
  droplet: Droplet,
  fish: Fish,
  leaf: Leaf,
  rabbit: Rabbit,
  tractor: Tractor,
  wheat: Wheat,
  trees: Trees,
  milk: Milk,
  sun: Sun,
  cloudRain: CloudRain,
  snowflake: Snowflake,
  flame: Flame,
  flask: FlaskConical,
  fileText: FileText,
  flameKindling: FlameKindling,
  palmtree: Palmtree,
  hexagon: Hexagon,
  component: Component,
  grid: Grid,
  tag: Tag,
  box: Box,
  store: Store,
  basket: ShoppingBasket,
  dollar: CircleDollarSign,
  trendingUp: TrendingUp,
  phone: Phone,
  smartphone: Smartphone,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  gift: Gift,
  key: Key,
  lock: Lock,
  upload: Upload,
  download: Download,
  pencil: Pencil,
  save: Save,
  megaphone: Megaphone,
  target: Target,
  briefcase: Briefcase,
  barChart: BarChart3,
  pieChart: PieChart,
  folder: Folder,
  users: Users,
  mail: Mail,
  inbox: Inbox,
  camera: Camera,
  sparkles: Sparkles,
  shieldCheck: ShieldCheck,
  crown: Crown,
  rocket: Rocket,
  coins: Coins,
  settings: Settings,
  ban: Ban,
  pause: Pause,
  zap: Zap,
  activity: Activity,
  eye: Eye,
  image: Image,
  calendar: Calendar,
  thermometer: Thermometer,
  microscope: Microscope,
  map: Map,
  filter: Filter,
  percent: Percent,
  hand: Hand,
  globe: Globe,
  refresh: RefreshCw,
  share: Share2,
  copy: Copy,
  file: File,
  layers: Layers,
  sliders: Sliders,
  thumbsUp: ThumbsUp,
  userCheck: UserCheck,
  shield: Shield,
  // — Aliases for call sites using alternate casing/naming (kept for compatibility) —
  "badge-check": BadgeCheck,
  "check-circle": CircleCheck,
  "chevron-down": ChevronDown,
  cpu: Cpu,
  document: FileText,
  edit: Pencil,
  "file-text": FileText,
  "git-merge": GitMerge,
  layoutDashboard: LayoutDashboard,
  loader: Loader2,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  paperclip: Paperclip,
  "shopping-bag": ShoppingBag,
  shoppingBag: ShoppingBag,
  smile: Smile,
  x: X,
  "trash-2": Trash2,
};

export default function Icon({ name, size = 18, strokeWidth = 1.8, className = "", ...props }) {
  if (!name) name = "info";

  // URL dəstəyi
  if (name.startsWith("http://") || name.startsWith("https://") || name.startsWith("/")) {
    return <img src={name} alt="icon" width={size} height={size} className={`object-contain ${className}`} {...props} />;
  }

  // Emoji dəstəyi (əgər Icon siyahısında yoxdursa və qısa mətndirsə)
  if (!ICONS[name] && name.length <= 4) {
    return <span className={className} style={{ fontSize: size, lineHeight: 1 }} {...props}>{name}</span>;
  }

  const IconComponent = ICONS[name] || Info;
  return <IconComponent size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...props} />;
}
